using Microsoft.EntityFrameworkCore;
using Domain.Entitites;

namespace Persistance.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }

        // Ensure DB has new columns when running without migrations (convenience during development).
        // Adds nullable integer column CriterioId to Comments if it doesn't exist.
        // This is safe to run repeatedly due to IF NOT EXISTS.
        public void EnsureSchemaCompat()
        {
            try
            {
                // Si existe un índice único antiguo que impide múltiples comentarios por voto, eliminarlo.
                Database.ExecuteSqlRaw("DROP INDEX IF EXISTS \"IX_Comments_VotoId\";");
                // Añadir la columna CriterioId si falta.
                Database.ExecuteSqlRaw("ALTER TABLE \"Comments\" ADD COLUMN IF NOT EXISTS \"CriterioId\" integer;");

                // Crear la tabla de premios en bases existentes donde aún no se aplicó la migración.
                Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS ""Premios"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""Emoji"" text NOT NULL,
                        ""Nombre"" text NOT NULL,
                        ""VotacionId"" integer NOT NULL,
                        ""ProyectoGanadorId"" integer NULL
                    );
                ");

                Database.ExecuteSqlRaw("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Premios_VotacionId\" ON \"Premios\" (\"VotacionId\");");
                Database.ExecuteSqlRaw("CREATE INDEX IF NOT EXISTS \"IX_Premios_ProyectoGanadorId\" ON \"Premios\" (\"ProyectoGanadorId\");");
            }
            catch (Exception ex)
            {
                // Log and continue - in production prefer proper migrations.
                Console.WriteLine($"Warning: could not ensure schema compatibility: {ex.Message}");
            }
        }

        // Aquí irás añadiendo tus entidades cuando las tengas
        public DbSet<Voto> Votes { get; set; }
        public DbSet<Usuario> Users { get; set; }
        public DbSet<Proyecto> Projects { get; set; }
        public DbSet<Comentario> Comments { get; set; }
        public DbSet<Evento> Events { get; set; }
        public DbSet<Votacion> Votaciones { get; set; }
        public DbSet<Premio> Premios { get; set; }
        public DbSet<ResumenIAProyecto> ResumenesIA { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // PATRÓN FÁBRICA - TPH para Evento — una sola tabla con columna discriminadora
            modelBuilder.Entity<Evento>()
                .HasDiscriminator<string>("TipoEvento")
                .HasValue<EstandarEvento>("Estandar")
                .HasValue<EsportsEvento>("Esports");
            // Cuando añadas más tipos: .HasValue<PresencialEvento>("Presencial")


            // PATRÓN FÁBRICA - TPH para Proyecto — una sola tabla con columna discriminadora
            modelBuilder.Entity<Proyecto>()
                .HasDiscriminator<string>("TipoProyecto")
                .HasValue<ProyectoEstandar>("Estandar");

            // TPH para Usuarios - Discriminador por Rol
            modelBuilder.Entity<Usuario>()
                .HasDiscriminator<string>("Rol")
                .HasValue<Concursante>("Concursante")
                .HasValue<Jurado>("Jurado")
                .HasValue<Administrador>("Administrador")
                .HasValue<Supervisor>("Supervisor");

            // Concursantes <-> Proyectos (N:M) — configurado explícitamente para que EF
            // emparejar correctamente Proyecto.Usuarios (tipo base Usuario) con
            // Concursante.ProyectosParticipados usando la tabla join "ProyectoConcursante".
            modelBuilder.Entity<Proyecto>()
                .HasMany(p => p.Usuarios)
                .WithMany("ProyectosParticipados")
                .UsingEntity(j => j.ToTable("ProyectoConcursante"));


            // Jurados asignados por votacion (N:N)
            modelBuilder.Entity<Votacion>()
                .HasMany(v => v.JuradosAsignados)
                .WithMany(j => j.VotacionesParticipadas);

            // Relacion 1:1 Votacion - Premio (unica tabla Premios con FK VotacionId)
            modelBuilder.Entity<Votacion>()
                .HasOne(v => v.Premio)
                .WithOne(p => p.Votacion)
                .HasForeignKey<Premio>(p => p.VotacionId)
                .OnDelete(DeleteBehavior.Cascade);

            // Premio -> Proyecto ganador (opcional)
            modelBuilder.Entity<Premio>()
                .HasOne(p => p.ProyectoGanador)
                .WithMany()
                .HasForeignKey(p => p.ProyectoGanadorId)
                .OnDelete(DeleteBehavior.SetNull);

            // Relación 1 a N entre Voto y Comentario: un voto puede tener múltiples comentarios (uno por criterio, más uno general)
            modelBuilder.Entity<Voto>()
                .HasMany(v => v.Comentarios)
                .WithOne(c => c.Voto)
                .HasForeignKey(c => c.VotoId)
                .OnDelete(DeleteBehavior.Cascade);
        }
        public void RemoveAllData()
        {
            // Orden correcto respetando FK: primero los dependientes, luego los principales
            Database.ExecuteSqlRaw("DELETE FROM \"Comments\"");
            Database.ExecuteSqlRaw("DELETE FROM \"Votes\"");
            Database.ExecuteSqlRaw("DELETE FROM \"Users\"");
            Database.ExecuteSqlRaw("DELETE FROM \"Premios\"");
            Database.ExecuteSqlRaw("DELETE FROM \"Votaciones\"");
            Database.ExecuteSqlRaw("DELETE FROM \"Projects\"");
            Database.ExecuteSqlRaw("DELETE FROM \"Events\"");
        }
    }
}