// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistance.Data;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524081110_ActualizacionEntidades")]
    partial class ActualizacionEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entitites.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CriterioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VotoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VotoId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Entitites.CriterioVotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VotacionId");

                    b.ToTable("CriterioVotacion");
                });

            modelBuilder.Entity("Domain.Entitites.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("TipoEvento").HasValue("Evento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entitites.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProyectoGanadorId")
                        .HasColumnType("integer");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoGanadorId");

                    b.HasIndex("VotacionId")
                        .IsUnique();

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("Domain.Entitites.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumenIA")
                        .HasColumnType("text");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Projects");

                    b.HasDiscriminator<string>("TipoProyecto").HasValue("Proyecto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entitites.ResumenIAProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("VotacionId");

                    b.ToTable("ResumenesIA");
                });

            modelBuilder.Entity("Domain.Entitites.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Contrasenya")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Rol").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entitites.Votacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcceso")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<List<string>>("DnisPermitidos")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("EsVotacionPopular")
                        .HasColumnType("boolean");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoComentarios")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxVotesPerVoter")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoVotacion")
                        .HasColumnType("integer");

                    b.Property<int?>("ValorMaximoNumerico")
                        .HasColumnType("integer");

                    b.Property<int>("eventoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("eventoId");

                    b.ToTable("Votaciones");
                });

            modelBuilder.Entity("Domain.Entitites.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CriterioValoracionesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaVotado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NombreUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProyId")
                        .HasColumnType("integer");

                    b.Property<int?>("Valoracion")
                        .HasColumnType("integer");

                    b.Property<int>("VotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuarioId");

                    b.HasIndex("ProyId");

                    b.HasIndex("VotacionId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("JuradoVotacion", b =>
                {
                    b.Property<int>("JuradosAsignadosId")
                        .HasColumnType("integer");

                    b.Property<int>("VotacionesParticipadasId")
                        .HasColumnType("integer");

                    b.HasKey("JuradosAsignadosId", "VotacionesParticipadasId");

                    b.HasIndex("VotacionesParticipadasId");

                    b.ToTable("JuradoVotacion");
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.Property<int>("ProyectosParticipadosId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("ProyectosParticipadosId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("ProyectoConcursante", (string)null);
                });

            modelBuilder.Entity("Domain.Entitites.EsportsEvento", b =>
                {
                    b.HasBaseType("Domain.Entitites.Evento");

                    b.Property<string>("Juego")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Esports");
                });

            modelBuilder.Entity("Domain.Entitites.EstandarEvento", b =>
                {
                    b.HasBaseType("Domain.Entitites.Evento");

                    b.HasDiscriminator().HasValue("Estandar");
                });

            modelBuilder.Entity("Domain.Entitites.ProyectoEstandar", b =>
                {
                    b.HasBaseType("Domain.Entitites.Proyecto");

                    b.HasDiscriminator().HasValue("Estandar");
                });

            modelBuilder.Entity("Domain.Entitites.Administrador", b =>
                {
                    b.HasBaseType("Domain.Entitites.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Domain.Entitites.Concursante", b =>
                {
                    b.HasBaseType("Domain.Entitites.Usuario");

                    b.HasDiscriminator().HasValue("Concursante");
                });

            modelBuilder.Entity("Domain.Entitites.Jurado", b =>
                {
                    b.HasBaseType("Domain.Entitites.Usuario");

                    b.HasDiscriminator().HasValue("Jurado");
                });

            modelBuilder.Entity("Domain.Entitites.Supervisor", b =>
                {
                    b.HasBaseType("Domain.Entitites.Usuario");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("Domain.Entitites.Comentario", b =>
                {
                    b.HasOne("Domain.Entitites.Voto", "Voto")
                        .WithMany("Comentarios")
                        .HasForeignKey("VotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voto");
                });

            modelBuilder.Entity("Domain.Entitites.CriterioVotacion", b =>
                {
                    b.HasOne("Domain.Entitites.Votacion", "Votacion")
                        .WithMany("Criterios")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Domain.Entitites.Premio", b =>
                {
                    b.HasOne("Domain.Entitites.Proyecto", "ProyectoGanador")
                        .WithMany()
                        .HasForeignKey("ProyectoGanadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entitites.Votacion", "Votacion")
                        .WithOne("Premio")
                        .HasForeignKey("Domain.Entitites.Premio", "VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProyectoGanador");

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Domain.Entitites.Proyecto", b =>
                {
                    b.HasOne("Domain.Entitites.Evento", "Evento")
                        .WithMany("proyectos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Domain.Entitites.ResumenIAProyecto", b =>
                {
                    b.HasOne("Domain.Entitites.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Votacion", "Votacion")
                        .WithMany()
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("Domain.Entitites.Votacion", b =>
                {
                    b.HasOne("Domain.Entitites.Evento", "evento")
                        .WithMany("votacion")
                        .HasForeignKey("eventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("evento");
                });

            modelBuilder.Entity("Domain.Entitites.Voto", b =>
                {
                    b.HasOne("Domain.Entitites.Usuario", "NombreUsuario")
                        .WithMany("voto")
                        .HasForeignKey("NombreUsuarioId");

                    b.HasOne("Domain.Entitites.Proyecto", "Proy")
                        .WithMany("VotosProyecto")
                        .HasForeignKey("ProyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Votacion", "Votacion")
                        .WithMany("Votos")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NombreUsuario");

                    b.Navigation("Proy");

                    b.Navigation("Votacion");
                });

            modelBuilder.Entity("JuradoVotacion", b =>
                {
                    b.HasOne("Domain.Entitites.Jurado", null)
                        .WithMany()
                        .HasForeignKey("JuradosAsignadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Votacion", null)
                        .WithMany()
                        .HasForeignKey("VotacionesParticipadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.HasOne("Domain.Entitites.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectosParticipadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitites.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entitites.Evento", b =>
                {
                    b.Navigation("proyectos");

                    b.Navigation("votacion");
                });

            modelBuilder.Entity("Domain.Entitites.Proyecto", b =>
                {
                    b.Navigation("VotosProyecto");
                });

            modelBuilder.Entity("Domain.Entitites.Usuario", b =>
                {
                    b.Navigation("voto");
                });

            modelBuilder.Entity("Domain.Entitites.Votacion", b =>
                {
                    b.Navigation("Criterios");

                    b.Navigation("Premio");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Domain.Entitites.Voto", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
